spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  tomcat:
    additional-tld-skip-patterns: "*.jar"
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    jsp:
      init-parameters:
        development: true